# Generated by Django 4.1.7 on 2023-03-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='products',
            name='client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.order'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
