# Generated by Django 4.1.7 on 2023-03-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_products_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
